[Icon Theme]
Name=Hicolor
Comment=Fallback icon theme
Hidden=true
Directories=32x32/apps,64x64/apps,128x128/apps,256x256/apps,scalable/apps

[32x32/apps]
Size=32
Context=Applications
Type=Threshold

[64x64/apps]
Size=64
Context=Applications
Type=Threshold

[128x128/apps]
Size=128
Context=Applications
Type=Threshold

[256x256/apps]
MinSize=64
Size=256
MaxSize=256
Context=Applications
Type=Scalable

[scalable/apps]
MinSize=1
Size=128
MaxSize=256
Context=Applications
Type=Scalable
